#+TITLE: ECG - anotações
#+AUTHOR: Gabriel Vieira

* Reunião 30/03/2021

- Qualquer comunicação sobre o ecg: mandar email pra Luana *E* para o prof. Zé Roberto.
- Pelo menos dois membros da banca devem ser docentes do ibqm.
- Ter critério na escolha da banca. Não pegar ngm mto próximo e talz... Tentar evitar ao máximo que a comissão de pós-graduação peçam mudança de membros da banca.
- Dá para enviar o tema/banca antes (manda com alguma antecedência) para a Luana e o zé roberto para que eles dêem um feedback sobre o que eles acham.
- Uma das coisas avaliadas pela banca é a pertinência dos artigos para a defesa daquele tema.
- O resumo deve ser completo o suficiente para convencer a CPG que aquele tema deva ser aprovado. O resumo é sobre os temas e não precisa ter as referências.
- Critérios para escolha: Tema que tivesse facilidade em ler/estudar.
- Não pense em mais nada durante o ECG. Foque SÓ NISSO!!!!
- Todos os dias úteis de junho estão disponíveis
- Preferencialmente, os ECGs são realizados na parte da tarde (14h). Mas, se estritamente necessário, basta entrar em contato com a Luana explicando o motivo.
- De preferência, os temas de ECG não devem ser os mesmos de alguns anos atrás. Tem a lista lá no site.
- Se algum membro da banca não puder no dia marcado, tudo bem. Dá para mudar o horário/data.
- Apresentação ECG: dia 25/06 (sexta-feira)
